service: Demo
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  stage: local
  region: ap-northeast-1
  logRetentionInDays: 30
  environment:
    STAGE: ${opt:stage}
    LOG_LEVEL: INFO

params:
  local:
    requirements_file: requirements/requirements_local.txt
  dev:
    requirements_file: requirements/requirements.txt

package:
  patterns:
    - "!**"
    - "src/**"

functions:
  hello:
    handler: src/hello.handler
    layers:  # Please comment out when deploy to localstack.
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:34
    environment:
      POWERTOOLS_SERVICE_NAME: DemoHelloFunction

custom:
  alerts:
    alarms:
      - functionErrors
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    fileName: ${param:requirements_file}
    usePipenv: false

plugins:
  - serverless-localstack
  - serverless-plugin-aws-alerts
  - serverless-prune-plugin
  - serverless-python-requirements
